FROM python:3.13-slim
WORKDIR /app
COPY . /app
    
RUN apt update -y && apt install -y awscli && apt clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt
CMD ["python3", "app.py"]