[project]
name = "endtoend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "catboost>=1.2.8",
    "dill>=0.4.0",
    "flask>=3.1.0",
    "scikit-learn>=1.6.1",
    "xgboost>=3.0.0",
]
